<?php
namespace Home\Controller;
use Think\Controller;
class StaticController extends Controller {
    public function get_tel(){
        $keyword = strtoupper($_POST['keyword']);
        $where = array(
            'name' => array('LIKE', "%$keyword%")
        );


        if("ko-kr" == cookie("lang")){
            $tel = M("static_tel")->field("id, sn, name_kr as name")->where($where)->select();
        }else{
            $tel = M("static_tel")->where($where)->select();
        }

        echo json_encode($tel);
    }
    public function get_country(){
        $keyword = strtoupper($_POST['keyword']);
        $where = array(
            'name' => array('LIKE', "%$keyword%")
        );

        if("ko-kr" == cookie("lang")){
            $country = M("static_country")->field("id, sn, name_kr as name")->where($where)->select();
        }else{
            $country = M("static_country")->where($where)->select();
        }
        echo json_encode($country);
    }
    public function get_money(){
        $keyword = strtoupper($_POST['keyword']);
        $where = array(
            'name' => array('LIKE', "%$keyword%")
        );

        if("ko-kr" == cookie("lang")){
            $money = M("static_money")->field("id, sn, name_kr as name")->where($where)->select();
        }else{
            $money = M("static_money")->where($where)->select();
        }
        echo json_encode($money);
    }

    public function get_pay_way(){
        $keyword = strtoupper($_POST['keyword']);
        $where = array(
            'name' => array('LIKE', "%$keyword%"),
            'status' => 0,
        );
        $pay_way = M("payway")->where($where)->select();
        echo json_encode($pay_way);
    }
    public function tel(){
        $arr = array(
          array("sn" => "244", "name" => "安哥拉 244"),
          array("sn" => "93", "name" => "阿富汗 93"),
          array("sn" => "355", "name" => "阿尔巴尼亚 355"),
          array("sn" => "213", "name" => "阿尔及利亚 213"),
          array("sn" => "376", "name" => "安道尔共和国 376"),
          array("sn" => "1264", "name" => "安圭拉岛 1264"),
          array("sn" => "1268", "name" => "安提瓜和巴布达 1268"),
          array("sn" => "54", "name" => "阿根廷 54"),
          array("sn" => "374", "name" => "亚美尼亚 374"),
          array("sn" => "247", "name" => "阿森松 247"),
          array("sn" => "61", "name" => "澳大利亚 61"),
          array("sn" => "43", "name" => "奥地利 43"),
          array("sn" => "994", "name" => "阿塞拜疆 994"),
          array("sn" => "1242", "name" => "巴哈马 1242"),
          array("sn" => "973", "name" => "巴林 973"),
          array("sn" => "880", "name" => "孟加拉国 880"),
          array("sn" => "1246", "name" => "巴巴多斯 1246"),
          array("sn" => "375", "name" => "白俄罗斯 375"),
          array("sn" => "32", "name" => "比利时 32"),
          array("sn" => "501", "name" => "伯利兹 501"),
          array("sn" => "229", "name" => "贝宁 229"),
          array("sn" => "1441", "name" => "百慕大群岛 1441"),
          array("sn" => "591", "name" => "玻利维亚 591"),
          array("sn" => "267", "name" => "博茨瓦纳 267"),
          array("sn" => "55", "name" => "巴西 55"),
          array("sn" => "673", "name" => "文莱 673"),
          array("sn" => "359", "name" => "保加利亚 359"),
          array("sn" => "226", "name" => "布基纳法索 226"),
          array("sn" => "95", "name" => "缅甸 95"),
          array("sn" => "257", "name" => "布隆迪 257"),
          array("sn" => "237", "name" => "喀麦隆 237"),
          array("sn" => "1", "name" => "加拿大 1"),
          array("sn" => "1345", "name" => "开曼群岛 1345"),
          array("sn" => "236", "name" => "中非共和国 236"),
          array("sn" => "235", "name" => "乍得 235"),
          array("sn" => "56", "name" => "智利 56"),
          array("sn" => "86", "name" => "中国 86"),
          array("sn" => "57", "name" => "哥伦比亚 57"),
          array("sn" => "242", "name" => "刚果 242"),
          array("sn" => "682", "name" => "库克群岛 682"),
          array("sn" => "506", "name" => "哥斯达黎加 506"),
          array("sn" => "53", "name" => "古巴 53"),
          array("sn" => "357", "name" => "塞浦路斯 357"),
          array("sn" => "420", "name" => "捷克 420"),
          array("sn" => "45", "name" => "丹麦 45"),
          array("sn" => "253", "name" => "吉布提 253"),
          array("sn" => "1890", "name" => "多米尼加共和国 1890"),
          array("sn" => "593", "name" => "厄瓜多尔 593"),
          array("sn" => "20", "name" => "埃及 20"),
          array("sn" => "503", "name" => "萨尔瓦多 503"),
          array("sn" => "372", "name" => "爱沙尼亚 372"),
          array("sn" => "251", "name" => "埃塞俄比亚 251"),
          array("sn" => "679", "name" => "斐济 679"),
          array("sn" => "358", "name" => "芬兰 358"),
          array("sn" => "33", "name" => "法国 33"),
          array("sn" => "594", "name" => "法属圭亚那 594"),
          array("sn" => "241", "name" => "加蓬 241"),
          array("sn" => "220", "name" => "冈比亚 220"),
          array("sn" => "995", "name" => "格鲁吉亚 995"),
          array("sn" => "49", "name" => "德国 49"),
          array("sn" => "233", "name" => "加纳 233"),
          array("sn" => "350", "name" => "直布罗陀 350"),
          array("sn" => "30", "name" => "希腊 30"),
          array("sn" => "1809", "name" => "格林纳达 1809"),
          array("sn" => "1671", "name" => "关岛 1671"),
          array("sn" => "502", "name" => "危地马拉 502"),
          array("sn" => "224", "name" => "几内亚 224"),
          array("sn" => "592", "name" => "圭亚那 592"),
          array("sn" => "509", "name" => "海地 509"),
          array("sn" => "504", "name" => "洪都拉斯 504"),
          array("sn" => "852", "name" => "中国香港 852"),
          array("sn" => "36", "name" => "匈牙利 36"),
          array("sn" => "354", "name" => "冰岛 354"),
          array("sn" => "91", "name" => "印度 91"),
          array("sn" => "62", "name" => "印度尼西亚 62"),
          array("sn" => "98", "name" => "伊朗 98"),
          array("sn" => "964", "name" => "伊拉克 964"),
          array("sn" => "353", "name" => "爱尔兰 353"),
          array("sn" => "972", "name" => "以色列 972"),
          array("sn" => "39", "name" => "意大利 39"),
          array("sn" => "225", "name" => "科特迪瓦 225"),
          array("sn" => "1876", "name" => "牙买加 1876"),
          array("sn" => "81", "name" => "日本 81"),
          array("sn" => "962", "name" => "约旦 962"),
          array("sn" => "855", "name" => "柬埔寨 855"),
          array("sn" => "327", "name" => "哈萨克斯坦 327"),
          array("sn" => "254", "name" => "肯尼亚 254"),
          array("sn" => "82", "name" => "韩国 82"),
          array("sn" => "965", "name" => "科威特 965"),
          array("sn" => "331", "name" => "吉尔吉斯坦 331"),
          array("sn" => "856", "name" => "老挝 856"),
          array("sn" => "371", "name" => "拉脱维亚 371"),
          array("sn" => "961", "name" => "黎巴嫩 961"),
          array("sn" => "266", "name" => "莱索托 266"),
          array("sn" => "231", "name" => "利比里亚 231"),
          array("sn" => "218", "name" => "利比亚 218"),
          array("sn" => "423", "name" => "列支敦士登 423"),
          array("sn" => "370", "name" => "立陶宛 370"),
          array("sn" => "352", "name" => "卢森堡 352"),
          array("sn" => "853", "name" => "中国澳门 853"),
          array("sn" => "261", "name" => "马达加斯加 261"),
          array("sn" => "265", "name" => "马拉维 265"),
          array("sn" => "60", "name" => "马来西亚 60"),
          array("sn" => "960", "name" => "马尔代夫 960"),
          array("sn" => "223", "name" => "马里 223"),
          array("sn" => "356", "name" => "马耳他 356"),
          array("sn" => "1670", "name" => "马里亚那群岛 1670"),
          array("sn" => "596", "name" => "马提尼克 596"),
          array("sn" => "230", "name" => "毛里求斯 230"),
          array("sn" => "52", "name" => "墨西哥 52"),
          array("sn" => "373", "name" => "摩尔多瓦 373"),
          array("sn" => "377", "name" => "摩纳哥 377"),
          array("sn" => "976", "name" => "蒙古 976"),
          array("sn" => "1664", "name" => "蒙特塞拉特岛 1664"),
          array("sn" => "212", "name" => "摩洛哥 212"),
          array("sn" => "258", "name" => "莫桑比克 258"),
          array("sn" => "264", "name" => "纳米比亚 264"),
          array("sn" => "674", "name" => "瑙鲁 674"),
          array("sn" => "977", "name" => "尼泊尔 977"),
          array("sn" => "599", "name" => "荷属安的列斯 599"),
          array("sn" => "31", "name" => "荷兰 31"),
          array("sn" => "64", "name" => "新西兰 64"),
          array("sn" => "505", "name" => "尼加拉瓜 505"),
          array("sn" => "227", "name" => "尼日尔 227"),
          array("sn" => "234", "name" => "尼日利亚 234"),
          array("sn" => "850", "name" => "朝鲜 850"),
          array("sn" => "47", "name" => "挪威 47"),
          array("sn" => "968", "name" => "阿曼 968"),
          array("sn" => "92", "name" => "巴基斯坦 92"),
          array("sn" => "507", "name" => "巴拿马 507"),
          array("sn" => "675", "name" => "巴布亚新几内亚 675"),
          array("sn" => "595", "name" => "巴拉圭 595"),
          array("sn" => "51", "name" => "秘鲁 51"),
          array("sn" => "63", "name" => "菲律宾 63"),
          array("sn" => "48", "name" => "波兰 48"),
          array("sn" => "689", "name" => "法属玻利尼西亚 689"),
          array("sn" => "351", "name" => "葡萄牙 351"),
          array("sn" => "1787", "name" => "波多黎各 1787"),
          array("sn" => "974", "name" => "卡塔尔 974"),
          array("sn" => "262", "name" => "留尼旺 262"),
          array("sn" => "40", "name" => "罗马尼亚 40"),
          array("sn" => "7", "name" => "俄罗斯 7"),
          array("sn" => "1758", "name" => "圣卢西亚 1758"),
          array("sn" => "1784", "name" => "圣文森特岛 1784"),
          array("sn" => "684", "name" => "东萨摩亚(美) 684"),
          array("sn" => "685", "name" => "西萨摩亚 685"),
          array("sn" => "378", "name" => "圣马力诺 378"),
          array("sn" => "239", "name" => "圣多美和普林西比 239"),
          array("sn" => "966", "name" => "沙特阿拉伯 966"),
          array("sn" => "221", "name" => "塞内加尔 221"),
          array("sn" => "248", "name" => "塞舌尔 248"),
          array("sn" => "232", "name" => "塞拉利昂 232"),
          array("sn" => "65", "name" => "新加坡 65"),
          array("sn" => "421", "name" => "斯洛伐克 421"),
          array("sn" => "386", "name" => "斯洛文尼亚 386"),
          array("sn" => "677", "name" => "所罗门群岛 677"),
          array("sn" => "252", "name" => "索马里 252"),
          array("sn" => "27", "name" => "南非 27"),
          array("sn" => "34", "name" => "西班牙 34"),
          array("sn" => "94", "name" => "斯里兰卡 94"),
          array("sn" => "1758", "name" => "圣卢西亚 1758"),
          array("sn" => "1784", "name" => "圣文森特 1784"),
          array("sn" => "249", "name" => "苏丹 249"),
          array("sn" => "597", "name" => "苏里南 597"),
          array("sn" => "268", "name" => "斯威士兰 268"),
          array("sn" => "46", "name" => "瑞典 46"),
          array("sn" => "41", "name" => "瑞士 41"),
          array("sn" => "963", "name" => "叙利亚 963"),
          array("sn" => "886", "name" => "中国台湾 886"),
          array("sn" => "992", "name" => "塔吉克斯坦 992"),
          array("sn" => "255", "name" => "坦桑尼亚 255"),
          array("sn" => "66", "name" => "泰国 66"),
          array("sn" => "228", "name" => "多哥 228"),
          array("sn" => "676", "name" => "汤加 676"),
          array("sn" => "1809", "name" => "特立尼达和多巴哥 1809"),
          array("sn" => "216", "name" => "突尼斯 216"),
          array("sn" => "90", "name" => "土耳其 90"),
          array("sn" => "993", "name" => "土库曼斯坦 993"),
          array("sn" => "256", "name" => "乌干达 256"),
          array("sn" => "380", "name" => "乌克兰 380"),
          array("sn" => "971", "name" => "阿拉伯联合酋长国 971"),
          array("sn" => "44", "name" => "英国 44"),
          array("sn" => "1", "name" => "美国 1"),
          array("sn" => "598", "name" => "乌拉圭 598"),
          array("sn" => "233", "name" => "乌兹别克斯坦 233"),
          array("sn" => "58", "name" => "委内瑞拉 58"),
          array("sn" => "84", "name" => "越南 84"),
          array("sn" => "967", "name" => "也门 967"),
          array("sn" => "381", "name" => "南斯拉夫 381"),
          array("sn" => "27", "name" => "南非 27"),
          array("sn" => "263", "name" => "津巴布韦 263"),
          array("sn" => "243", "name" => "扎伊尔 243"),
          array("sn" => "260", "name" => "赞比亚 260"),
        );
        foreach($arr as $key => $val){
//            M("static_tel")->add($val);
        }
    }
    public function guojia(){
        $arr = array(array("sn" => "AO", "name" => "AO  安哥拉"),
            array("sn" => "AF", "name" => "AF  阿富汗"),
            array("sn" => "AL", "name" => "AL  阿尔巴尼亚"),
            array("sn" => "DZ", "name" => "DZ  阿尔及利亚"),
            array("sn" => "AD", "name" => "AD  安道尔共和国"),
            array("sn" => "AI", "name" => "AI  安圭拉岛"),
            array("sn" => "AG", "name" => "AG  安提瓜和巴布达"),
            array("sn" => "AR", "name" => "AR  阿根廷"),
            array("sn" => "AM", "name" => "AM  亚美尼亚"),
            array("sn" => "AU", "name" => "AU  澳大利亚"),
            array("sn" => "AT", "name" => "AT  奥地利"),
            array("sn" => "AZ", "name" => "AZ  阿塞拜疆"),
            array("sn" => "BS", "name" => "BS  巴哈马"),
            array("sn" => "BH", "name" => "BH  巴林"),
            array("sn" => "BD", "name" => "BD  孟加拉国"),
            array("sn" => "BB", "name" => "BB  巴巴多斯"),
            array("sn" => "BY", "name" => "BY  白俄罗斯"),
            array("sn" => "BE", "name" => "BE  比利时"),
            array("sn" => "BZ", "name" => "BZ  伯利兹"),
            array("sn" => "BJ", "name" => "BJ  贝宁"),
            array("sn" => "BM", "name" => "BM  百慕大群岛"),
            array("sn" => "BO", "name" => "BO  玻利维亚"),
            array("sn" => "BW", "name" => "BW  博茨瓦纳"),
            array("sn" => "BR", "name" => "BR  巴西"),
            array("sn" => "BN", "name" => "BN  文莱"),
            array("sn" => "BG", "name" => "BG  保加利亚"),
            array("sn" => "BF", "name" => "BF  布基纳法索"),
            array("sn" => "MM", "name" => "MM  缅甸"),
            array("sn" => "BI", "name" => "BI  布隆迪"),
            array("sn" => "CM", "name" => "CM  喀麦隆"),
            array("sn" => "CA", "name" => "CA  加拿大"),
            array("sn" => "CF", "name" => "CF  中非共和国"),
            array("sn" => "TD", "name" => "TD  乍得"),
            array("sn" => "CL", "name" => "CL  智利"),
            array("sn" => "CN", "name" => "CN  中国"),
            array("sn" => "CG", "name" => "CG  刚果"),
            array("sn" => "CK", "name" => "CK  库克群岛"),
            array("sn" => "CR", "name" => "CR  哥斯达黎加"),
            array("sn" => "CU", "name" => "CU  古巴"),
            array("sn" => "CY", "name" => "CY  塞浦路斯"),
            array("sn" => "CZ", "name" => "CZ  捷克"),
            array("sn" => "DK", "name" => "DK  丹麦"),
            array("sn" => "DJ", "name" => "DJ  吉布提"),
            array("sn" => "DO", "name" => "DO  多米尼加共和国"),
            array("sn" => "EC", "name" => "EC  厄瓜多尔"),
            array("sn" => "EG", "name" => "EG  埃及"),
            array("sn" => "SV", "name" => "SV  萨尔瓦多"),
            array("sn" => "EE", "name" => "EE  爱沙尼亚"),
            array("sn" => "ET", "name" => "ET  埃塞俄比亚"),
            array("sn" => "FJ", "name" => "FJ  斐济"),
            array("sn" => "FI", "name" => "FI  芬兰"),
            array("sn" => "FR", "name" => "FR  法国"),
            array("sn" => "GF", "name" => "GF  法属圭亚那"),
            array("sn" => "GA", "name" => "GA  加蓬"),
            array("sn" => "GM", "name" => "GM  冈比亚"),
            array("sn" => "GE", "name" => "GE  格鲁吉亚"),
            array("sn" => "DE", "name" => "DE  德国"),
            array("sn" => "GH", "name" => "GH  加纳"),
            array("sn" => "GI", "name" => "GI  直布罗陀"),
            array("sn" => "GR", "name" => "GR  希腊"),
            array("sn" => "GD", "name" => "GD  格林纳达"),
            array("sn" => "GU", "name" => "GU  关岛"),
            array("sn" => "GT", "name" => "GT  危地马拉"),
            array("sn" => "GN", "name" => "GN  几内亚"),
            array("sn" => "GY", "name" => "GY  圭亚那"),
            array("sn" => "HT", "name" => "HT  海地"),
            array("sn" => "HN", "name" => "HN  洪都拉斯"),
            array("sn" => "HK", "name" => "HK  中国香港"),
            array("sn" => "HU", "name" => "HU  匈牙利"),
            array("sn" => "IS", "name" => "IS  冰岛"),
            array("sn" => "IN", "name" => "IN  印度"),
            array("sn" => "ID", "name" => "ID  印度尼西亚"),
            array("sn" => "IR", "name" => "IR  伊朗"),
            array("sn" => "IQ", "name" => "IQ  伊拉克"),
            array("sn" => "IE", "name" => "IE  爱尔兰"),
            array("sn" => "IL", "name" => "IL  以色列"),
            array("sn" => "IT", "name" => "IT  意大利"),
            array("sn" => "JM", "name" => "JM  牙买加"),
            array("sn" => "JP", "name" => "JP  日本"),
            array("sn" => "JO", "name" => "JO  约旦"),
            array("sn" => "KH", "name" => "KH  柬埔寨"),
            array("sn" => "KZ", "name" => "KZ  哈萨克斯坦"),
            array("sn" => "KE", "name" => "KE  肯尼亚"),
            array("sn" => "KR", "name" => "KR  韩国"),
            array("sn" => "KW", "name" => "KW  科威特"),
            array("sn" => "KG", "name" => "KG  吉尔吉斯坦"),
            array("sn" => "LA", "name" => "LA  老挝"),
            array("sn" => "LV", "name" => "LV  拉脱维亚"),
            array("sn" => "LB", "name" => "LB  黎巴嫩"),
            array("sn" => "LS", "name" => "LS  莱索托"),
            array("sn" => "LR", "name" => "LR  利比里亚"),
            array("sn" => "LY", "name" => "LY  利比亚"),
            array("sn" => "LI", "name" => "LI  列支敦士登"),
            array("sn" => "LT", "name" => "LT  立陶宛"),
            array("sn" => "LU", "name" => "LU  卢森堡"),
            array("sn" => "MO", "name" => "MO  中国澳门"),
            array("sn" => "MG", "name" => "MG  马达加斯加"),
            array("sn" => "MW", "name" => "MW  马拉维"),
            array("sn" => "MY", "name" => "MY  马来西亚"),
            array("sn" => "MV", "name" => "MV  马尔代夫"),
            array("sn" => "ML", "name" => "ML  马里"),
            array("sn" => "MT", "name" => "MT  马耳他"),
            array("sn" => "MU", "name" => "MU  毛里求斯"),
            array("sn" => "MX", "name" => "MX  墨西哥"),
            array("sn" => "MD", "name" => "MD  摩尔多瓦"),
            array("sn" => "MC", "name" => "MC  摩纳哥"),
            array("sn" => "MN", "name" => "MN  蒙古"),
            array("sn" => "MS", "name" => "MS  蒙特塞拉特岛"),
            array("sn" => "MA", "name" => "MA  摩洛哥"),
            array("sn" => "MZ", "name" => "MZ  莫桑比克"),
            array("sn" => "NA", "name" => "NA  纳米比亚"),
            array("sn" => "NR", "name" => "NR  瑙鲁"),
            array("sn" => "NP", "name" => "NP  尼泊尔"),
            array("sn" => "NL", "name" => "NL  荷兰"),
            array("sn" => "NZ", "name" => "NZ  新西兰"),
            array("sn" => "NI", "name" => "NI  尼加拉瓜"),
            array("sn" => "NE", "name" => "NE  尼日尔"),
            array("sn" => "NG", "name" => "NG  尼日利亚"),
            array("sn" => "KP", "name" => "KP  朝鲜"),
            array("sn" => "NO", "name" => "NO  挪威"),
            array("sn" => "OM", "name" => "OM  阿曼"),
            array("sn" => "PK", "name" => "PK  巴基斯坦"),
            array("sn" => "PA", "name" => "PA  巴拿马"),
            array("sn" => "PG", "name" => "PG  巴布亚新几内亚"),
            array("sn" => "PY", "name" => "PY  巴拉圭"),
            array("sn" => "PE", "name" => "PE  秘鲁"),
            array("sn" => "PH", "name" => "PH  菲律宾"),
            array("sn" => "PL", "name" => "PL  波兰"),
            array("sn" => "PF", "name" => "PF  法属玻利尼西亚"),
            array("sn" => "PT", "name" => "PT  葡萄牙"),
            array("sn" => "PR", "name" => "PR  波多黎各"),
            array("sn" => "QA", "name" => "QA  卡塔尔"),
            array("sn" => "RO", "name" => "RO  罗马尼亚"),
            array("sn" => "RU", "name" => "RU  俄罗斯"),
            array("sn" => "LC", "name" => "LC  圣卢西亚"),
            array("sn" => "VC", "name" => "VC  圣文森特岛"),
            array("sn" => "SM", "name" => "SM  圣马力诺"),
            array("sn" => "ST", "name" => "ST  圣多美和普林西比"),
            array("sn" => "SA", "name" => "SA  沙特阿拉伯"),
            array("sn" => "SN", "name" => "SN  塞内加尔"),
            array("sn" => "SC", "name" => "SC  塞舌尔"),
            array("sn" => "SL", "name" => "SL  Leone  塞拉利昂"),
            array("sn" => "SG", "name" => "SG  新加坡"),
            array("sn" => "SK", "name" => "SK  斯洛伐克"),
            array("sn" => "SI", "name" => "SI  斯洛文尼亚"),
            array("sn" => "SB", "name" => "SB  所罗门群岛"),
            array("sn" => "SO", "name" => "SO  索马里"),
            array("sn" => "ZA", "name" => "ZA  南非"),
            array("sn" => "ES", "name" => "ES  西班牙"),
            array("sn" => "LK", "name" => "LK  斯里兰卡"),
            array("sn" => "LC", "name" => "LC  圣卢西亚"),
            array("sn" => "VC", "name" => "VC  圣文森特"),
            array("sn" => "SD", "name" => "SD  苏丹"),
            array("sn" => "SR", "name" => "SR  苏里南"),
            array("sn" => "SZ", "name" => "SZ  斯威士兰"),
            array("sn" => "SE", "name" => "SE  瑞典"),
            array("sn" => "CH", "name" => "CH  瑞士"),
            array("sn" => "SY", "name" => "SY  叙利亚"),
            array("sn" => "TW", "name" => "TW  中国台湾"),
            array("sn" => "TJ", "name" => "TJ  塔吉克斯坦"),
            array("sn" => "TZ", "name" => "TZ  坦桑尼亚"),
            array("sn" => "TH", "name" => "TH  泰国"),
            array("sn" => "TG", "name" => "TG  多哥"),
            array("sn" => "TO", "name" => "TO  汤加"),
            array("sn" => "TT", "name" => "TT  特立尼达和多巴哥"),
            array("sn" => "TN", "name" => "TN  突尼斯"),
            array("sn" => "TR", "name" => "TR  土耳其"),
            array("sn" => "TM", "name" => "TM  土库曼斯坦"),
            array("sn" => "UG", "name" => "UG  乌干达"),
            array("sn" => "UA", "name" => "UA  乌克兰"),
            array("sn" => "AE", "name" => "AE  阿拉伯联合酋长国"),
            array("sn" => "GB", "name" => "GB  英国"),
            array("sn" => "US", "name" => "US  美国"),
            array("sn" => "UY", "name" => "UY  乌拉圭"),
            array("sn" => "UZ", "name" => "UZ  乌兹别克斯坦"),
            array("sn" => "VE", "name" => "VE  委内瑞拉"),
            array("sn" => "VN", "name" => "VN  越南"),
            array("sn" => "YE", "name" => "YE  也门"),
            array("sn" => "YU", "name" => "YU  南斯拉夫"),
            array("sn" => "ZW", "name" => "ZW  津巴布韦"),
            array("sn" => "ZR", "name" => "ZR  扎伊尔"),
            array("sn" => "ZM", "name" => "ZM  赞比亚")
        );
        foreach($arr as $key => $val){
//            M("static_country")->add($val);
        }
    }
    public function money(){
        $arr = array(
            array("sn" => "AED", "name" => "AED  阿联酋迪拉姆"),
            array("sn" => "AFN", "name" => "AFN  阿富汗尼"),
            array("sn" => "ALL", "name" => "ALL  阿尔巴尼列克"),
            array("sn" => "AMD", "name" => "AMD  亚美尼亚德拉姆"),
            array("sn" => "ANG", "name" => "ANG  荷兰盾"),
            array("sn" => "AOA", "name" => "AOA  安哥拉宽扎"),
            array("sn" => "ARS", "name" => "ARS  阿根廷比索"),
            array("sn" => "AUD", "name" => "AUD  澳元"),
            array("sn" => "AWG", "name" => "AWG  阿鲁巴弗罗林"),
            array("sn" => "AZN", "name" => "AZN  阿塞拜疆马纳特"),
            array("sn" => "BAM", "name" => "BAM  波黑可兑换马克"),
            array("sn" => "BBD", "name" => "BBD  巴巴多斯元"),
            array("sn" => "BDT", "name" => "BDT  孟加拉国塔卡"),
            array("sn" => "BGN", "name" => "BGN  保加利亚列弗"),
            array("sn" => "BHD", "name" => "BHD  巴林第纳尔"),
            array("sn" => "BIF", "name" => "BIF  布隆迪法郎"),
            array("sn" => "BMD", "name" => "BMD  百慕大元"),
            array("sn" => "BND", "name" => "BND  文莱元"),
            array("sn" => "BOB", "name" => "BOB  玻利维亚诺"),
            array("sn" => "BRL", "name" => "BRL  巴西雷亚尔"),
            array("sn" => "BSD", "name" => "BSD  巴哈马元"),
            array("sn" => "BTN", "name" => "BTN  不丹努扎姆"),
            array("sn" => "BWP", "name" => "BWP  博茨瓦纳普拉"),
            array("sn" => "BYN", "name" => "BYN  新白俄罗斯卢布"),
            array("sn" => "BYR", "name" => "BYR  白俄罗斯卢布"),
            array("sn" => "BZD", "name" => "BZD  伯利兹元"),
            array("sn" => "CAD", "name" => "CAD  加元"),
            array("sn" => "CDF", "name" => "CDF  刚果法郎"),
            array("sn" => "CHF", "name" => "CHF  瑞士法郎"),
            array("sn" => "CLF", "name" => "CLF  智利比索(基金)"),
            array("sn" => "CLP", "name" => "CLP  智利比索"),
            array("sn" => "CNY", "name" => "CNY  人民币"),
            array("sn" => "COP", "name" => "COP  哥伦比亚比索"),
            array("sn" => "CRC", "name" => "CRC  哥斯达黎加科朗"),
            array("sn" => "CUP", "name" => "CUP  古巴比索"),
            array("sn" => "CVE", "name" => "CVE  佛得角埃斯库多"),
            array("sn" => "CZK", "name" => "CZK  捷克克朗"),
            array("sn" => "DJF", "name" => "DJF  吉布提法郎"),
            array("sn" => "DKK", "name" => "DKK  丹麦克朗"),
            array("sn" => "DOP", "name" => "DOP  多米尼加比索"),
            array("sn" => "DZD", "name" => "DZD  阿尔及利亚第纳尔"),
            array("sn" => "EGP", "name" => "EGP  埃及镑"),
            array("sn" => "ERN", "name" => "ERN  厄立特里亚纳克法"),
            array("sn" => "ETB", "name" => "ETB  埃塞俄比亚比尔"),
            array("sn" => "EUR", "name" => "EUR  欧元"),
            array("sn" => "FJD", "name" => "FJD  斐济元"),
            array("sn" => "FKP", "name" => "FKP  福克兰群岛镑"),
            array("sn" => "GBP", "name" => "GBP  英镑"),
            array("sn" => "GEL", "name" => "GEL  格鲁吉亚拉里"),
            array("sn" => "GHS", "name" => "GHS  加纳塞地"),
            array("sn" => "GIP", "name" => "GIP  直布罗陀镑"),
            array("sn" => "GMD", "name" => "GMD  冈比亚达拉西"),
            array("sn" => "GNF", "name" => "GNF  几内亚法郎"),
            array("sn" => "GTQ", "name" => "GTQ  危地马拉格查尔"),
            array("sn" => "GYD", "name" => "GYD  圭亚那元"),
            array("sn" => "HKD", "name" => "HKD  港币"),
            array("sn" => "HNL", "name" => "HNL  洪都拉斯伦皮拉"),
            array("sn" => "HRK", "name" => "HRK  克罗地亚库纳"),
            array("sn" => "HTG", "name" => "HTG  海地古德"),
            array("sn" => "HUF", "name" => "HUF  匈牙利福林"),
            array("sn" => "IDR", "name" => "IDR  印度尼西亚卢比"),
            array("sn" => "ILS", "name" => "ILS  以色列新谢克尔"),
            array("sn" => "INR", "name" => "INR  印度卢比"),
            array("sn" => "IQD", "name" => "IQD  伊拉克第纳尔"),
            array("sn" => "IRR", "name" => "IRR  伊朗里亚尔"),
            array("sn" => "ISK", "name" => "ISK  冰岛克郎"),
            array("sn" => "JMD", "name" => "JMD  牙买加元"),
            array("sn" => "JOD", "name" => "JOD  约旦第纳尔"),
            array("sn" => "JPY", "name" => "JPY  日元"),
            array("sn" => "KES", "name" => "KES  肯尼亚先令"),
            array("sn" => "KGS", "name" => "KGS  吉尔吉斯斯坦索姆"),
            array("sn" => "KHR", "name" => "KHR  柬埔寨瑞尔"),
            array("sn" => "KMF", "name" => "KMF  科摩罗法郎"),
            array("sn" => "KPW", "name" => "KPW  朝鲜元"),
            array("sn" => "KRW", "name" => "KRW  韩元"),
            array("sn" => "KWD", "name" => "KWD  科威特第纳尔"),
            array("sn" => "KYD", "name" => "KYD  开曼群岛元"),
            array("sn" => "KZT", "name" => "KZT  哈萨克斯坦坚戈"),
            array("sn" => "LAK", "name" => "LAK  老挝基普"),
            array("sn" => "LBP", "name" => "LBP  黎巴嫩镑"),
            array("sn" => "LKR", "name" => "LKR  斯里兰卡卢比"),
            array("sn" => "LRD", "name" => "LRD  利比里亚元"),
            array("sn" => "LSL", "name" => "LSL  莱索托洛蒂"),
            array("sn" => "LYD", "name" => "LYD  利比亚第纳尔"),
            array("sn" => "MAD", "name" => "MAD  摩洛哥迪拉姆"),
            array("sn" => "MDL", "name" => "MDL  摩尔多瓦列伊"),
            array("sn" => "MGA", "name" => "MGA  马达加斯加阿里亚里"),
            array("sn" => "MKD", "name" => "MKD  马其顿代纳尔"),
            array("sn" => "MMK", "name" => "MMK  缅甸元"),
            array("sn" => "MNT", "name" => "MNT  蒙古图格里克"),
            array("sn" => "MOP", "name" => "MOP  澳门元"),
            array("sn" => "MRO", "name" => "MRO  毛里塔尼亚乌吉亚"),
            array("sn" => "MUR", "name" => "MUR  毛里求斯卢比"),
            array("sn" => "MVR", "name" => "MVR  马尔代夫拉菲亚"),
            array("sn" => "MWK", "name" => "MWK  马拉维克瓦查"),
            array("sn" => "MXN", "name" => "MXN  墨西哥比索"),
            array("sn" => "MXV", "name" => "MXV  墨西哥(资金)"),
            array("sn" => "MYR", "name" => "MYR  林吉特"),
            array("sn" => "MZN", "name" => "MZN  莫桑比克新梅蒂卡尔"),
            array("sn" => "NAD", "name" => "NAD  纳米比亚元"),
            array("sn" => "NGN", "name" => "NGN  尼日利亚奈拉"),
            array("sn" => "NIO", "name" => "NIO  尼加拉瓜新科多巴"),
            array("sn" => "NOK", "name" => "NOK  挪威克朗"),
            array("sn" => "NPR", "name" => "NPR  尼泊尔卢比"),
            array("sn" => "NZD", "name" => "NZD  新西兰元"),
            array("sn" => "OMR", "name" => "OMR  阿曼里亚尔"),
            array("sn" => "PAB", "name" => "PAB  巴拿马巴波亚"),
            array("sn" => "PEN", "name" => "PEN  秘鲁新索尔"),
            array("sn" => "PGK", "name" => "PGK  巴布亚新几内亚基那"),
            array("sn" => "PHP", "name" => "PHP  菲律宾比索"),
            array("sn" => "PKR", "name" => "PKR  巴基斯坦卢比"),
            array("sn" => "PLN", "name" => "PLN  波兰兹罗提"),
            array("sn" => "PYG", "name" => "PYG  巴拉圭瓜拉尼"),
            array("sn" => "QAR", "name" => "QAR  卡塔尔里亚尔"),
            array("sn" => "RON", "name" => "RON  罗马尼亚列伊"),
            array("sn" => "RSD", "name" => "RSD  塞尔维亚第纳尔"),
            array("sn" => "RUB", "name" => "RUB  俄罗斯卢布"),
            array("sn" => "RWF", "name" => "RWF  卢旺达法郎"),
            array("sn" => "SAR", "name" => "SAR  沙特里亚尔"),
            array("sn" => "SBD", "name" => "SBD  所罗门群岛元"),
            array("sn" => "SCR", "name" => "SCR  塞舌尔卢比"),
            array("sn" => "SDG", "name" => "SDG  苏丹磅"),
            array("sn" => "SEK", "name" => "SEK  瑞典克朗"),
            array("sn" => "SGD", "name" => "SGD  新加坡元"),
            array("sn" => "SHP", "name" => "SHP  圣赫勒拿镑"),
            array("sn" => "SLL", "name" => "SLL  塞拉利昂利昂"),
            array("sn" => "SOS", "name" => "SOS  索马里先令"),
            array("sn" => "SRD", "name" => "SRD  苏里南元"),
            array("sn" => "SSP", "name" => "SSP  南苏丹镑"),
            array("sn" => "STD", "name" => "STD  圣多美多布拉"),
            array("sn" => "SVC", "name" => "SVC  萨尔瓦多科朗"),
            array("sn" => "SYP", "name" => "SYP  叙利亚镑"),
            array("sn" => "SZL", "name" => "SZL  斯威士兰里兰吉尼"),
            array("sn" => "THB", "name" => "THB  泰铢"),
            array("sn" => "TJS", "name" => "TJS  塔吉克斯坦索莫尼"),
            array("sn" => "TMT", "name" => "TMT  土库曼斯坦马纳特"),
            array("sn" => "TND", "name" => "TND  突尼斯第纳尔"),
            array("sn" => "TOP", "name" => "TOP  汤加潘加"),
            array("sn" => "TRY", "name" => "TRY  土耳其里拉"),
            array("sn" => "TTD", "name" => "TTD  特立尼达多巴哥元"),
            array("sn" => "TWD", "name" => "TWD  新台币"),
            array("sn" => "TZS", "name" => "TZS  坦桑尼亚先令"),
            array("sn" => "UAH", "name" => "UAH  乌克兰格里夫纳"),
            array("sn" => "UGX", "name" => "UGX  乌干达先令"),
            array("sn" => "USD", "name" => "USD  美元"),
            array("sn" => "UYU", "name" => "UYU  乌拉圭比索"),
            array("sn" => "UZS", "name" => "UZS  乌兹别克斯坦苏姆"),
            array("sn" => "VEF", "name" => "VEF  委内瑞拉玻利瓦尔"),
            array("sn" => "VND", "name" => "VND  越南盾"),
            array("sn" => "VUV", "name" => "VUV  瓦努阿图瓦图"),
            array("sn" => "WST", "name" => "WST  萨摩亚塔拉"),
            array("sn" => "XAF", "name" => "XAF  中非法郎"),
            array("sn" => "XAG", "name" => "XAG  银价盎司"),
            array("sn" => "XAU", "name" => "XAU  金价盎司"),
            array("sn" => "XCD", "name" => "XCD  东加勒比元"),
            array("sn" => "XDR", "name" => "XDR  IMF特别提款权"),
            array("sn" => "XOF", "name" => "XOF  西非法郎"),
            array("sn" => "XPD", "name" => "XPD  钯价盎司"),
            array("sn" => "XPF", "name" => "XPF  太平洋法郎"),
            array("sn" => "XPT", "name" => "XPT  珀价盎司"),
            array("sn" => "YER", "name" => "YER  也门里亚尔"),
            array("sn" => "ZAR", "name" => "ZAR  南非兰特"),
            array("sn" => "ZMW", "name" => "ZMW  赞比亚克瓦查"),
            array("sn" => "ZWL", "name" => "ZWL  津巴布韦元"),
            array("sn" => "GGP", "name" => "GGP  根西岛镑"),
        );

        foreach($arr as $key => $val){
            M("static_money")->add($val);
        }
          
    }
}